### ISSUE TITLE
multithreaded casa

### ISSUE THREAD

**Issue by caseyjlaw** [pkgw/pwkit#10]
This is more of a report than an issue, but I found that a pattern I developed in using CASA tools is not thread safe.
The issue arises when I write a function that uses measures to calculate uvw coordinates. My pattern was to instantiate the measures object once and call the function elsewhere in the Python module. Multithreading this would end up crashing while calling the uvw calculation, since threads were operating on the same measures object.
My solution is to instantiate the measures object each time I want to calculate uvw.

**Comment by caseyjlaw** [comment]
Correction, my solution does not work. I chatted with a CASA developer and they confirmed that CASA measures is not thread safe as it has some weird statefulness.
This is a corner issue for pwkit, but hopefully this issue serves as a warning to others. I'll close this.

**Comment by pkgw** [comment]
Thanks for filing. In principle, pwkit could add some locking that would attempt to prevent clashing access to things. But I think that would be a losing battle, and Python is just not going to be that friendly to multithreading in general. [Rust, on the other hand](https://github.com/pkgw/rubbl) ...
