### ISSUE TITLE
Citable Version?

### ISSUE THREAD

**Issue by augustfly** [pkgw/pwkit#5]
We have pwkit linked in a submitted manuscript, and I was wondering if you had a preferred citation for it that we could recommend to authors. Could you also put that in the repo ReadMe? Thanks.

**Comment by pkgw** [comment]
Sorry for taking a while to get on this. I've registered it with the ASCL, which I believe should eventually mint a DOI, etc. [The link is here](http://ascl.net/code/v/1654) although I'm not sure if that's some temporary thing that will change once the record is formalized.

**Comment by augustfly** [comment]
Great! We will use the ASCL entry for the preferred citation. I think that you're right that the stable URL is TBD, but this is good enough for now. Thanks, Peter.

**Comment by pkgw** [comment]
As a follow-up, the ASCL record has been created: http://ascl.net/1704.001 .
