### ISSUE TITLE
measures functions return incomplete data structures

### ISSUE THREAD

**Issue by caseyjlaw** [pkgw/pwkit#6]
It seems that the CASA 4.7 bindings (or CASA itself) have somehow changed such that measures functions return a subset of all the calculation. In full CASA 4.7 (that is, "casapy"), I can set up a calculation of uvw coordinates (using me.doframe) and then calculate antenna uvw like this:

```
CASA <13>: me.touvw(bls)
  Out[13]: 
({'m0': {'unit': 'rad',
         'value': array([ 1.65855232,  1.53084045,  1.43570213])},
  'm1': {'unit': 'rad',
         'value': array([-0.45440347, -0.52948073, -0.57718908])},
  'm2': {'unit': 'm',
         'value': array([ 6.70820393,  8.1240384 ,  9.64365076])},
  'refer': 'J2000',
  'type': 'uvw'},
 {'unit': 'm',
  'value': array([-0.52826847,  6.00428142, -2.94440775,  0.28008048,  7.00601327,
       -4.10333194,  1.08842944,  8.00774511, -5.26225614])},
 {'unit': 'm/s',
  'value': array([ -2.13538724e-04,  -0.00000000e+00,   3.83118730e-05,
        -2.97587951e-04,   0.00000000e+00,  -2.03124138e-05,
        -3.81637177e-04,   0.00000000e+00,  -7.89367006e-05])})
```

This returns a tuple with three objects. The second one is useful for rtpipe uvw calculation. This worked identically in CASA 4.6 and casa-python 4.6. Now, this is what is returned for casa-python 4.7:

```
In [20]: me.touvw(bls)
Out[20]: 
{'m0': {'unit': 'rad',
  'value': array([ 1.65855232,  1.53084045,  1.43570213])},
 'm1': {'unit': 'rad',
  'value': array([-0.45440347, -0.52948073, -0.57718908])},
 'm2': {'unit': 'm', 'value': array([ 6.70820393,  8.1240384 ,  9.64365076])},
 'refer': 'J2000',
 'type': 'uvw'}
```

I noticed that another function (me.expand) also should return a tuple, but instead returns a dict. It suggests some low-level change in CASA 4.7 data structures.

The CASA 4.7 release notes do not mention any changes along these lines, but I did submit a helpdesk ticket asking about this.

**Comment by pkgw** [comment]
@caseyjlaw Which build of the casa-python package are you using? I discovered some problems in the first versions (before build `4.7.2_3`) in an area of the code that might be related. Although, I *think* that the parts of it that might be relevant to this issue should still be working.

If this still occurs in the `4.7.2_3` build, can you provide me with a quick test case to reproduce? That might only be as much effort as it takes to report what the `bls` variable above looks like, if there isn't any extra setup that needs to be done.

Thanks for reporting and your patience — the transition to 4.7.x, including my changes to add Python 3 support, have been much rockier than hoped.

**Comment by caseyjlaw** [comment]
I am running this one: casa-python 4.7.2 np112py27_3 pkgw-forge.

This should reproduce the issue:

```
me.doframe(me.observatory('VLA'))
me.doframe(me.epoch('utc', '2015/01/01/00:00:00'))
me.doframe(me.direction('J2000', '0deg', '0deg'))
antpos = me.position('itrf', qa.quantity([0,1], 'm'), qa.quantity([1,2], 'm'), qa.quantity([3,4], 'm'))
bls = me.asbaseline(antpos)
```

Then ```me.touvw(bls)``` returns a single dict, rather than a tuple of three dicts.
Thanks for looking into it. I'm running ok on 4.6 for now, but am avoiding any updates.

**Comment by pkgw** [comment]
OK, thanks! You caught a fairly esoteric issue. I believe that I have identified and fixed the problem. (See the commit that GitHub noticed above.) Update Linux packages (version `np112py27_4`) are now available, and I'm building OSX packages now. Please reopen if you still see issues with 4.7 next time you take a look.

**Comment by caseyjlaw** [comment]
Looks good!
